[package]
name = "wee"
version = "0.1.0"
authors = ["Aster <galaster@foxmail.com>"]
edition = "2018"


[dependencies]
clap = { version = "3.0.0-beta.1", features = ["yaml"] }
toml = "0.5"


[scripts]
update = "cargo update"
install = "cargo install --path ."
publish = "cargo publish"