[package]
name = "wee"
version = "0.2.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/GalAster/wee"
license = "MPL-2.0"


[dependencies]
clap = { version = "3.0.0-beta.1"}
toml = "0.5"
serde_json = "1.0"
colored = "1.9"

[scripts]
update = "cargo update"
install = "cargo install --path ."
publish = """
cargo publish
cargo gg
"""